<?php

declare(strict_types=1);

namespace Algoritma\CodingStandards\Installer\Writer;

use Nette\Neon\Neon;

final class PhpstanConfigWriter implements PhpCsConfigWriterInterface
{
    public function writeConfigFile(?string $filename = null, bool $noDev = false, bool $noRisky = false): void
    {
        $filename = $filename ?: 'phpstan.neon';
        file_put_contents($filename, $this->createConfigSource());
        file_put_contents(dirname($filename) . '/algoritma-phpstan-config.php', $this->createAlgoritmaConfigFile($noDev));
    }

    private function createConfigSource(): string
    {
        return Neon::encode([
            'includes' => [
                'algoritma-phpstan-config.php',
            ],
            'parameters' => [
                'level' => 6,
                'excludePaths' => [
                    '**/node_modules/*',
                    '**/vendor/*',
                ],
            ],
        ], true);
        // Returns $value converted to multiline NEON
    }

    private function createAlgoritmaConfigFile(bool $noDev): string
    {
        $providersLine = [
            '    new Algoritma\CodingStandards\Rules\PhpstanRulesProvider(),',
        ];
        $providersLine[] = '    new Algoritma\CodingStandards\Rules\ArrayRulesProvider($additionalRules),';
        $providersLine = implode("\n", $providersLine);

        $rulesProviderConfig = <<<EOD
            \$additionalRules = [];
            \$rulesProvider = new Algoritma\\CodingStandards\\Rules\\CompositeRulesProvider([
            {$providersLine}
            ]);
            EOD;

        $autoloadPathProvider = '$autoloadPathProvider = new Algoritma\CodingStandards\AutoloadPathProvider();';

        if ($noDev) {
            $autoloadPathProvider = '$autoloadPathProvider = new Algoritma\CodingStandards\AutoloadPathProvider(null, null, false);';
        }

        return <<<EOD
            <?php
            /**
             * Autogenerated Configuration. DO NOT EDIT.
             */
            {$autoloadPathProvider}
            
            {$rulesProviderConfig}
            
            /**
             * Paths need to be absolute only on PHP Coniguration.
             */
            \$paths = array_map(
                static function(string \$path) {
                    return \\Symfony\\Component\\Filesystem\\Path::makeAbsolute(\$path), __DIR__);
                }, \$autoloadPathProvider->getPaths());

            \$paths = array_values(array_unique(\$paths));
            
            return [
                'parameters' => [
                    'paths' => \$paths,
                    'treatPhpDocTypesAsCertain' => false,
                    'inferPrivatePropertyTypeFromConstructor' => true,
                    'type_perfect' => [
                        'no_mixed_property' => true,
                        'no_mixed_caller' => true,
                        'null_over_false' => true,
                        'narrow_param' => true,
                        'narrow_return' => true,
                    ],
                    'errorFormat' => 'ticketswap',
                    'editorUrl' => 'phpstorm://open?file=%%file%%&line=%%line%%',
                ],
                'rules' => \$rulesProvider->getRules()
            ];

            EOD;
    }
}
