<?php

declare(strict_types=1);

namespace Algoritma\CodingStandardsTest\Installer\Writer;

use Algoritma\CodingStandards\Installer\Writer\PhpstanAlgoritmaConfigWriter;
use Algoritma\CodingStandardsTest\Framework\TestCase;
use org\bovigo\vfs\vfsStream;
use org\bovigo\vfs\vfsStreamDirectory;

class PhpstanAlgoritmaConfigWriterTest extends TestCase
{
    private vfsStreamDirectory $vfsRoot;

    protected function setUp(): void
    {
        parent::setUp();

        $this->vfsRoot = vfsStream::setup();
    }

    public function testWriteConfigFile(): void
    {
        $filename = $this->vfsRoot->url() . '/phpstan-algoritma-config.php';

        $writer = new PhpstanAlgoritmaConfigWriter();

        $writer->writeConfigFile($filename);

        $content = file_get_contents($filename);

        $expected
            = <<<'EOD'
                <?php
                /**
                 * Autogenerated Configuration. DO NOT EDIT.
                 */
                $autoloadPathProvider = new Algoritma\CodingStandards\AutoloadPathProvider();

                $additionalRules = [];
                $rulesProvider = new Algoritma\CodingStandards\Rules\CompositeRulesProvider([
                    new Algoritma\CodingStandards\Rules\PhpstanRulesProvider(),
                    new Algoritma\CodingStandards\Rules\ArrayRulesProvider($additionalRules),
                ]);
                
                /**
                 * Paths need to be absolute only on PHP Configuration.
                 */
                $paths = array_map(
                    static function(string $path) {
                        return \Symfony\Component\Filesystem\Path::makeAbsolute($path, __DIR__);
                    }, $autoloadPathProvider->getPaths());

                $paths = array_values(array_unique($paths));

                return [
                    'parameters' => [
                        'paths' => $paths,
                        'treatPhpDocTypesAsCertain' => false,
                        'inferPrivatePropertyTypeFromConstructor' => true,
                        'type_perfect' => [
                            'no_mixed_property' => true,
                            'no_mixed_caller' => true,
                            'null_over_false' => true,
                            'narrow_param' => true,
                            'narrow_return' => true,
                        ],
                        'errorFormat' => 'ticketswap',
                        'editorUrl' => 'phpstorm://open?file=%%file%%&line=%%line%%',
                    ],
                    'rules' => $rulesProvider->getRules()
                ];

                EOD;

        self::assertSame($expected, $content);
    }

    public function testWriteConfigFileWithNoDev(): void
    {
        $filename = $this->vfsRoot->url() . '/phpstan-algoritma-config.php';
        $writer = new PhpstanAlgoritmaConfigWriter();

        $writer->writeConfigFile($filename, true);

        $content = file_get_contents($filename);

        $expected
            = <<<'EOD'
                <?php
                /**
                 * Autogenerated Configuration. DO NOT EDIT.
                 */
                $autoloadPathProvider = new Algoritma\CodingStandards\AutoloadPathProvider(null, null, false);
                
                $additionalRules = [];
                $rulesProvider = new Algoritma\CodingStandards\Rules\CompositeRulesProvider([
                    new Algoritma\CodingStandards\Rules\PhpstanRulesProvider(),
                    new Algoritma\CodingStandards\Rules\ArrayRulesProvider($additionalRules),
                ]);
                
                /**
                 * Paths need to be absolute only on PHP Configuration.
                 */
                $paths = array_map(
                    static function(string $path) {
                        return \Symfony\Component\Filesystem\Path::makeAbsolute($path, __DIR__);
                    }, $autoloadPathProvider->getPaths());

                $paths = array_values(array_unique($paths));

                return [
                    'parameters' => [
                        'paths' => $paths,
                        'treatPhpDocTypesAsCertain' => false,
                        'inferPrivatePropertyTypeFromConstructor' => true,
                        'type_perfect' => [
                            'no_mixed_property' => true,
                            'no_mixed_caller' => true,
                            'null_over_false' => true,
                            'narrow_param' => true,
                            'narrow_return' => true,
                        ],
                        'errorFormat' => 'ticketswap',
                        'editorUrl' => 'phpstorm://open?file=%%file%%&line=%%line%%',
                    ],
                    'rules' => $rulesProvider->getRules()
                ];

                EOD;

        self::assertSame($expected, $content);
    }
}
