<?php

declare(strict_types=1);

namespace Algoritma\CodingStandards\Phpstan\Writer;

final class PhpstanAlgoritmaConfigWriter implements PhpstanConfigWriterInterface
{
    public function writeConfigFile(?string $filename = null, bool $noDev = false, bool $noRisky = false): void
    {
        $filename = $filename ?: 'phpstan-algoritma-config.php';
        file_put_contents($filename, $this->createAlgoritmaConfigFile($noDev));
    }

    private function createAlgoritmaConfigFile(bool $noDev): string
    {
        $providersLine = [
            '    new Algoritma\CodingStandards\Phpstan\Rules\PhpstanRulesProvider(),',
        ];
        $providersLine[] = '    new Algoritma\CodingStandards\Shared\Rules\ArrayRulesProvider($additionalRules),';
        $providersLine = implode("\n", $providersLine);

        $rulesProviderConfig = <<<EOD
            \$additionalRules = [];
            \$rulesProvider = new Algoritma\\CodingStandards\\Shared\\Rules\\CompositeRulesProvider([
            {$providersLine}
            ]);
            EOD;

        $autoloadPathProvider = '$autoloadPathProvider = new Algoritma\CodingStandards\AutoloadPathProvider();';

        if ($noDev) {
            $autoloadPathProvider = '$autoloadPathProvider = new Algoritma\CodingStandards\AutoloadPathProvider(null, null, false);';
        }

        return <<<EOD
            <?php
            /**
             * Autogenerated Configuration. DO NOT EDIT.
             */
            {$autoloadPathProvider}
            
            {$rulesProviderConfig}
            
            /**
             * Paths need to be absolute only on PHP Configuration.
             */
            \$paths = array_map(
                static function(string \$path) {
                    return \\Symfony\\Component\\Filesystem\\Path::makeAbsolute(\$path, __DIR__);
                }, \$autoloadPathProvider->getPaths());

            \$paths = array_values(array_unique(\$paths));
            
            return [
                'parameters' => [
                    'paths' => \$paths,
                    'treatPhpDocTypesAsCertain' => false,
                    'inferPrivatePropertyTypeFromConstructor' => true,
                    'type_perfect' => [
                        'no_mixed_property' => true,
                        'no_mixed_caller' => true,
                        'null_over_false' => true,
                        'narrow_param' => true,
                        'narrow_return' => true,
                    ],
                    'errorFormat' => 'ticketswap',
                    'editorUrl' => 'phpstorm://open?file=%%file%%&line=%%line%%',
                ],
                'rules' => \$rulesProvider->getRules()
            ];

            EOD;
    }
}
